version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    command: uvicorn main:app --reload --host 0.0.0.0 --port 8000
  frontend:
    build: ./frontend
    ports:
      - "8080:8080"
    depends_on:
      - backend
